import { useState } from 'react';
import { Sparkles, Menu, X, ArrowUpRight } from 'lucide-react';
import Hero from './components/Hero';
import Lore from './components/Lore';
import Grimoire from './components/Grimoire';
import CharacterCard from './components/CharacterCard';
import Gallery from './components/Gallery';
import { characters } from './data/frierenData';
export default function App(){const [menu,setMenu]=useState(false);const [party,setParty]=useState<'Semua'|'Pahlawan'|'Sekarang'>('Semua');return <><a className="skip-link" href="#main">Lewati ke konten</a><header><nav className="page-width nav" aria-label="Navigasi utama"><a href="#home" className="brand" aria-label="Frieren beranda"><Sparkles size={24} strokeWidth={1.1}/><div>FRIEREN<small>BEYOND JOURNEY’S END</small></div></a><button className="mobile-menu icon-button" aria-label={menu?'Tutup menu':'Buka menu'} aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div id="navigation" className={`nav-links ${menu?'is-open':''}`}>{[['Kisah','lore'],['Grimoire','grimoire'],['Sahabat','companions'],['Kenangan','memories']].map(([name,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{name}</a>)}</div><a className="nav-cta" href="#memories">Jelajahi dunia <ArrowUpRight size={15}/></a></nav></header><main id="main"><Hero/><Lore/><Grimoire/><section id="companions" className="section page-width"><div className="section-top"><div><div className="eyebrow">03 — MEREKA YANG BERARTI</div><h2>Perjalanan berubah.<br/><em>Ikatan tetap tinggal.</em></h2></div><p className="section-aside">Ada yang berjalan di sisi kita.<br/>Ada yang hidup dalam ingatan kita.<br/>Semuanya menjadi bagian dari cerita.</p></div><div className="filters">{(['Semua','Pahlawan','Sekarang'] as const).map(p=><button key={p} aria-pressed={party===p} className={party===p?'active':''} onClick={()=>setParty(p)}>{p==='Semua'?'Semua sahabat':`Party ${p}`}</button>)}</div><div className="character-grid">{characters.filter(c=>party==='Semua'||c.party===party).map(c=><CharacterCard key={c.name} character={c}/>)}</div><p className="placeholder-note">Potret placeholder · Kutipan diadaptasi secara kreatif</p></section><Gallery/><section className="closing"><Sparkles size={28} strokeWidth={1}/><p>Perjalanan belum berakhir.</p><h2>Masih banyak hal kecil<br/><em>yang layak ditemukan.</em></h2><a href="#home">Kembali ke awal <ArrowUpRight size={15}/></a></section></main><footer className="page-width"><a className="footer-brand" href="#home">FRIEREN <Sparkles size={15}/></a><p>Sebuah penghormatan kecil untuk perjalanan yang besar.</p><small>Ga Tau Gabur By Bian</small></footer></>}
